apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  namespace: robot
  labels:
    app: postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deploy
  template:
    metadata:
      labels:
        app: postgres-deploy
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: postgres:17.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: PGDATA
              value: /var/lib/postgresql/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/new_data
              name: postgres-storage


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: robot
  labels:
    app: postgres-deploy
spec:
  selector:
    app: postgres-deploy
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP