apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: agent-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: robot
  labels:
    type: local
spec:
  storageClassName: agent-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi